[0.973s] Invoking command in '/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/gps_package': AMENT_PREFIX_PATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/gps_package:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/gps_package/pytest.xml --junit-prefix=gps_package -o cache_dir=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/gps_package/.pytest_cache PYTHONPATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/gps_package/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
[2.435s] [1m============================= test session starts ==============================[0m
[2.435s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[2.435s] cachedir: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/gps_package/.pytest_cache
[2.435s] rootdir: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/gps_package
[2.435s] plugins: ament-xmllint-0.14.1, ament-copyright-0.14.1, ament-flake8-0.14.1, launch-testing-2.0.2, ament-pep257-0.14.1, launch-testing-ros-0.24.0, ament-lint-0.14.1, colcon-core-0.12.1, cov-3.0.0
[2.435s] [1mcollecting ... [0m[1m
[2.435s] collected 3 items                                                              [0m
[2.435s] 
[2.435s] test/test_copyright.py [33ms[0m[32m                                                 [ 33%][0m
[2.436s] test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
[2.436s] test/test_pep257.py [32m.[0m[31m                                                    [100%][0m
[2.436s] 
[2.436s] =================================== FAILURES ===================================
[2.436s] [31m[1m_________________________________ test_flake8 __________________________________[0m
[2.436s] [1m[31mtest/test_flake8.py[0m:23: in test_flake8
[2.436s]     [94massert[39;49;00m rc == [94m0[39;49;00m, \
[2.436s] [1m[31mE   AssertionError: Found 3 code style errors / warnings:[0m
[2.436s] [1m[31mE     ./gps_package/gps_node copy.py:59:77: E203 whitespace before ':'[0m
[2.436s] [1m[31mE     ./gps_package/gps_node.py:55:77: E203 whitespace before ':'[0m
[2.436s] [1m[31mE     ./gps_package/gps_node.py:104:1: E305 expected 2 blank lines after class or function definition, found 1[0m
[2.436s] [1m[31mE   assert 1 == 0[0m
[2.436s] ----------------------------- Captured stdout call -----------------------------
[2.436s] 
[2.436s] ./gps_package/gps_node copy.py:59:77: E203 whitespace before ':'
[2.436s]                     self.received_data = self.received_data[sentence_end + 2 :]
[2.436s]                                                                             ^
[2.436s] 
[2.436s] ./gps_package/gps_node.py:55:77: E203 whitespace before ':'
[2.436s]                     self.received_data = self.received_data[sentence_end + 2 :]
[2.436s]                                                                             ^
[2.436s] 
[2.436s] ./gps_package/gps_node.py:104:1: E305 expected 2 blank lines after class or function definition, found 1
[2.436s] if __name__ == "__main__":
[2.437s] ^
[2.437s] 
[2.437s] 2     E203 whitespace before ':'
[2.437s] 1     E305 expected 2 blank lines after class or function definition, found 1
[2.437s] 
[2.437s] 7 files checked
[2.437s] 3 errors
[2.437s] 
[2.437s] 'E'-type errors: 3
[2.437s] 
[2.437s] Checked files:
[2.437s] 
[2.437s] * ./setup.py
[2.437s] * ./test/test_flake8.py
[2.437s] * ./test/test_pep257.py
[2.437s] * ./test/test_copyright.py
[2.437s] * ./gps_package/__init__.py
[2.437s] * ./gps_package/gps_node copy.py
[2.437s] * ./gps_package/gps_node.py
[2.437s] ----------------------------- Captured stderr call -----------------------------
[2.437s] option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
[2.437s] - generated xml file: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/gps_package/pytest.xml -
[2.437s] =========================== short test summary info ============================
[2.438s] FAILED test/test_flake8.py::test_flake8 - AssertionError: Found 3 code style ...
[2.438s] [31m============== [31m[1m1 failed[0m, [32m1 passed[0m, [33m1 skipped[0m, [33m2 warnings[0m[31m in 0.20s[0m[31m ==============[0m
[2.438s] [33m=============================== warnings summary ===============================[0m
[2.438s] test/test_flake8.py::test_flake8
[2.438s] test/test_flake8.py::test_flake8
[2.438s]   Warning: SelectableGroups dict interface is deprecated. Use select.
[2.438s] 
[2.438s] -- Docs: https://docs.pytest.org/en/stable/warnings.html
[2.962s] Invoked command in '/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/gps_package' returned '1': AMENT_PREFIX_PATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/gps_package:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/gps_package/pytest.xml --junit-prefix=gps_package -o cache_dir=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/gps_package/.pytest_cache PYTHONPATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/gps_package/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
