[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/.pytest_cache
rootdir: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/control_package
plugins: ament-xmllint-0.14.1, ament-copyright-0.14.1, ament-flake8-0.14.1, launch-testing-2.0.2, ament-pep257-0.14.1, launch-testing-ros-0.24.0, ament-lint-0.14.1, colcon-core-0.12.1, cov-3.0.0
[1mcollecting ... [0m[1m
collected 3 items                                                              [0m

test/test_copyright.py [33ms[0m[32m                                                 [ 33%][0m
test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
test/test_pep257.py [32m.[0m[31m                                                    [100%][0m

=================================== FAILURES ===================================
[31m[1m_________________________________ test_flake8 __________________________________[0m
[1m[31mtest/test_flake8.py[0m:23: in test_flake8
    [94massert[39;49;00m rc == [94m0[39;49;00m, \
[1m[31mE   AssertionError: Found 12 code style errors / warnings:[0m
[1m[31mE     ./control_package/control_node.py:4:1: F401 'random' imported but unused[0m
[1m[31mE     ./control_package/control_node.py:9:22: E231 missing whitespace after ','[0m
[1m[31mE     ./control_package/control_node.py:11:1: W293 blank line contains whitespace[0m
[1m[31mE     ./control_package/control_node.py:22:9: E265 block comment should start with '# '[0m
[1m[31mE     ./control_package/control_node.py:66:1: E303 too many blank lines (4)[0m
[1m[31mE     ./control_package/control_node.py:71:60: E231 missing whitespace after ','[0m
[1m[31mE     ./control_package/control_node.py:72:54: E231 missing whitespace after ','[0m
[1m[31mE     ./control_package/control_node.py:73:50: E231 missing whitespace after ','[0m
[1m[31mE     ./control_package/control_node.py:79:9: E265 block comment should start with '# '[0m
[1m[31mE     ./control_package/control_node.py:80:9: E265 block comment should start with '# '[0m
[1m[31mE     ./control_package/control_node.py:81:1: W293 blank line contains whitespace[0m
[1m[31mE     ./control_package/control_node.py:90:11: W292 no newline at end of file[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stdout call -----------------------------

./control_package/control_node.py:4:1: F401 'random' imported but unused
import random
^

./control_package/control_node.py:9:22: E231 missing whitespace after ','
    def __init__(self,node):
                     ^

./control_package/control_node.py:11:1: W293 blank line contains whitespace
    
^

./control_package/control_node.py:22:9: E265 block comment should start with '# '
        #print("SUB:",self.parsed_sub_data)
        ^

./control_package/control_node.py:66:1: E303 too many blank lines (4)
def main(args=None):
^

./control_package/control_node.py:71:60: E231 missing whitespace after ','
    control_node.init_battery_data_publisher("battery_data",1)
                                                           ^

./control_package/control_node.py:72:54: E231 missing whitespace after ','
    control_node.init_mppt_data_publisher("mppt_data",1)
                                                     ^

./control_package/control_node.py:73:50: E231 missing whitespace after ','
    control_node.init_mc_data_publisher("mc_data",1)
                                                 ^

./control_package/control_node.py:79:9: E265 block comment should start with '# '
        #control_node.mppt_pub_data = control_node.parsed_sub_data[59:115]
        ^

./control_package/control_node.py:80:9: E265 block comment should start with '# '
        #control_node.mc_pub_data = control_node.parsed_sub_data[115:123]
        ^

[33m=============================== warnings summary ===============================[0m
test/test_flake8.py::test_flake8
test/test_flake8.py::test_flake8
  Warning: SelectableGroups dict interface is deprecated. Use select.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
./control_package/control_node.py:81:1: W293 blank line contains whitespace
        
^

./control_package/control_node.py:90:11: W292 no newline at end of file
    main()          ^

4     E231 missing whitespace after ','
3     E265 block comment should start with '# '
1     E303 too many blank lines (4)
1     F401 'random' imported but unused
1     W292 no newline at end of file
2     W293 blank line contains whitespace

6 files checked
12 errors

'E'-type errors: 8
'F'-type errors: 1
'W'-type errors: 3

Checked files:

* ./setup.py
* ./test/test_flake8.py
* ./test/test_pep257.py
* ./test/test_copyright.py
* ./control_package/__init__.py
* ./control_package/control_node.py
----------------------------- Captured stderr call -----------------------------
option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
- generated xml file: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/pytest.xml -
=========================== short test summary info ============================
FAILED test/test_flake8.py::test_flake8 - AssertionError: Found 12 code style...
[31m============== [31m[1m1 failed[0m, [32m1 passed[0m, [33m1 skipped[0m, [33m2 warnings[0m[31m in 0.20s[0m[31m ==============[0m
